
IF NOT EXISTS(SELECT 1 FROM [sys].[databases] WHERE [name] = N'ItineraryPlanner')
BEGIN
	CREATE DATABASE [ItineraryPlanner]
	 CONTAINMENT = NONE
	 ON  PRIMARY 
	( NAME = N'ItineraryPlanner', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ItineraryPlanner.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
	 LOG ON 
	( NAME = N'ItineraryPlanner_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\ItineraryPlanner_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)

	ALTER DATABASE [ItineraryPlanner] SET COMPATIBILITY_LEVEL = 120

	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin
	EXEC [ItineraryPlanner].[dbo].[sp_fulltext_database] @action = 'enable'
	end

	ALTER DATABASE [ItineraryPlanner] SET ANSI_NULL_DEFAULT OFF 

	ALTER DATABASE [ItineraryPlanner] SET ANSI_NULLS OFF 

	ALTER DATABASE [ItineraryPlanner] SET ANSI_PADDING OFF 

	ALTER DATABASE [ItineraryPlanner] SET ANSI_WARNINGS OFF 

	ALTER DATABASE [ItineraryPlanner] SET ARITHABORT OFF 

	ALTER DATABASE [ItineraryPlanner] SET AUTO_CLOSE OFF 

	ALTER DATABASE [ItineraryPlanner] SET AUTO_SHRINK OFF 

	ALTER DATABASE [ItineraryPlanner] SET AUTO_UPDATE_STATISTICS ON 

	ALTER DATABASE [ItineraryPlanner] SET CURSOR_CLOSE_ON_COMMIT OFF 

	ALTER DATABASE [ItineraryPlanner] SET CURSOR_DEFAULT  GLOBAL 

	ALTER DATABASE [ItineraryPlanner] SET CONCAT_NULL_YIELDS_NULL OFF 

	ALTER DATABASE [ItineraryPlanner] SET NUMERIC_ROUNDABORT OFF 

	ALTER DATABASE [ItineraryPlanner] SET QUOTED_IDENTIFIER OFF 

	ALTER DATABASE [ItineraryPlanner] SET RECURSIVE_TRIGGERS OFF 

	ALTER DATABASE [ItineraryPlanner] SET  DISABLE_BROKER 

	ALTER DATABASE [ItineraryPlanner] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

	ALTER DATABASE [ItineraryPlanner] SET DATE_CORRELATION_OPTIMIZATION OFF 

	ALTER DATABASE [ItineraryPlanner] SET TRUSTWORTHY OFF 

	ALTER DATABASE [ItineraryPlanner] SET ALLOW_SNAPSHOT_ISOLATION OFF 

	ALTER DATABASE [ItineraryPlanner] SET PARAMETERIZATION SIMPLE 

	ALTER DATABASE [ItineraryPlanner] SET READ_COMMITTED_SNAPSHOT OFF 

	ALTER DATABASE [ItineraryPlanner] SET HONOR_BROKER_PRIORITY OFF 

	ALTER DATABASE [ItineraryPlanner] SET RECOVERY FULL 

	ALTER DATABASE [ItineraryPlanner] SET  MULTI_USER 

	ALTER DATABASE [ItineraryPlanner] SET PAGE_VERIFY CHECKSUM  

	ALTER DATABASE [ItineraryPlanner] SET DB_CHAINING OFF 

	ALTER DATABASE [ItineraryPlanner] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

	ALTER DATABASE [ItineraryPlanner] SET TARGET_RECOVERY_TIME = 0 SECONDS 

	ALTER DATABASE [ItineraryPlanner] SET DELAYED_DURABILITY = DISABLED 

	ALTER DATABASE [ItineraryPlanner] SET  READ_WRITE 

END